name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 23 * * *'

jobs:

  # BUILD, TEST COVERAGE, SNYK, LINT,
  install-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install ðŸ”§
      run:
        npm i
    - name: Test Coverage ðŸ§ª
      run:
        npm run test-coverage
    - name: ESLint ðŸš¨
      run:
        npm run lint
      env:
        CI: true
    - name: Code Coverage (CodeCov) ðŸ™ˆ
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
    - name: Code Coverage - CodeClimate ðŸ—»
      uses: paambaati/codeclimate-action@v2.3.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_TOKEN}}
      with:
        coverageCommand: npm run test-coverage
        debug: true
